name: app_boilerplate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  injectable: ^3.0.0
  auto_route: ^11.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dev: ^1.0.0
  dio: ^5.9.2
  retrofit: ^4.9.2
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.1.1
  web_socket_channel: ^3.0.3
  dartz: ^0.10.1
  retrofit_generator: ^10.2.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.3.1
  cached_network_image: ^3.4.1
  lottie: ^3.3.3
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.5
  json_annotation: ^4.12.0
  # easy_localization: ^3.0.8
  # shared_preferences: ^2.5.5

dev_dependencies:
  auto_route_generator: ^10.5.0
  build_runner: ^2.15.0
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8
  flutter_test:
    sdk: flutter
  injectable_generator: ^3.0.2
  json_serializable: ^6.14.0

flutter:
  assets:
    - assets/images/
    - assets/translations/
    
  uses-material-design: true



flutter_native_splash:
  color: "#1c1c1c"
  image: assets/images/logo.png
  
  # برای اینکه در حالت دارک مود هم مشکلی نباشد (اگر لوگوی جداگانه دارید)
  # image_dark: assets/images/logo_white.png 

  android: true
  ios: true
  
  # تنظیمات اختصاصی اندروید ۱۲
  android_12:
    image: assets/images/logo.png
    color: "#1c1c1c"
    # icon_background_color: "#1c1c1c" # اگر آیکون شما شفاف است
    
  # غیرفعال کردن وضعیت تمام صفحه اگر می‌خواهید Status Bar گوشی نمایش داده شود
  fullscreen: false 

